services:
  - type: web
    name: musicbot
    env: python
    plan: free
    buildCommand: "apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: AUDD_TOKEN
        sync: false
