services:
  - type: web
    name: musicbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: "8684337468:AAGhQ6rjhtvX-pUuYfmtnrA7SMVHIciIG6Q"
      - key: ADMIN_IDS
        value: "5599261398"
      - key: PYTHON_VERSION
        value: "3.10.12"
