services:
  - type: worker
    name: musicbot
    env: python
    plan: free
    buildCommand: "apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "python main.py"
    disk:
      name: musicbot-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: AUDD_TOKEN
        sync: false
